spring.application.name=SpringSecurityMySqlAuthDemo


#configure server port with different id
server.port=8080

#configure db properties
spring.datasource.url=jdbc:mysql://localhost:3306/project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Praveen@9640

#configure hibernate and jpa properties
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update

# Mail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=praaveeeen5@gmail.com
spring.mail.password=zswv oqle cfnk vrhh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true